---
- name: Installation de packages via snap
  become: yes
  command: "snap install {{ item }} --classic"
  with_items:
   - code
   - microk8s
  # snap:
  #   name:
  #     - code
  #     - microk8s
  #   classic: yes
